### ISSUE TITLE
AndroidQ blacklist question

### ISSUE THREAD

**Issue by TomGarden** [retrostreams/android-retrofuture#3]
## In Android project(For AndroidQ) , USE the lib view check 3 blacklist api, check tool is : [veridex-tool](https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces#test-veridex-tool) :

**Is this problem will be fix ?** 

**problem output log :**  

```java
#66: Reflection blacklist Ljava/util/HashMap$EntrySet;->this$0 use(s):
       Ljava9/util/HMSpliterators;-><clinit>()V

#67: Reflection blacklist Ljava/util/HashMap$KeySet;->this$0 use(s):
       Ljava9/util/HMSpliterators;-><clinit>()V

#68: Reflection blacklist Ljava/util/HashMap$Values;->this$0 use(s):
       Ljava9/util/HMSpliterators;-><clinit>()V
```

**Comment by stefan-zobel** [comment]
Hi Tom,

no, unfortunately I don't think that there is much that can be done in this particular case.

Regards,
Stefan

**Edit**: Well, probably it could be done. I'm not sure / would have to investigate.
(This is not a promise to deliver that soon - I'm in a kind of "hibernation mode" right now.)

**Comment by stefan-zobel** [comment]
Hi Tom,

it would be possible to guarantee that the code in question will never get called on Android Q or above.
Thus, code that creates streams from collections produced from HashMap or HashSet would still work on API level >= 29.

But a static code analysis tool like veridex would nevertheless report a blacklist violation since it wouldn't be able to detect that this particular code path is never executed when running on API level >= 29.

Is that sufficient for you?

Regards,
Stefan

**Comment by stefan-zobel** [comment]
The code in question that is flagged by the veridex tool doesn't get executed on API >= 26, so nothing bad could happen at runtime. What happens is that the formation of Spliterators is delegated to the platform Spliterator implementation when the runtime offers one.
As I said, static analysis tools won't be able to detect that which is why the blacklist violation is a false positive. I don't intend to change anything here.

**Comment by TomGarden** [comment]
Copy that！
Thank you very much.
Your reply will help many other developers.
I had fix my problem by RxJava.
Thank you again.
